import type { NextPage, GetStaticPropsResult } from 'next';
import Head from 'next/head';
import axios from 'axios';
import Container from '@mui/material/Container';

import { Product } from '@/domain/product/Product';

import { AppBar } from '@/ui/components/general/AppBar';
import { ProductListItem } from '@/ui/components/products/ProductListItem';
import styles from '@/ui/styles/Home.module.css';

type Props = {
  products: Product[];
};

const Home: NextPage<Props> = ({ products, ...otherProps }) => {
  return (
    <>
      <Head>
        <title>My dummy store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <AppBar {...otherProps} />
        <Container maxWidth="xl" className={styles.container}>
          {products.map(product => (
            <ProductListItem key={product.id} product={product} />
          ))}
        </Container>
      </main>
    </>
  );
};

export async function getStaticProps(): Promise<GetStaticPropsResult<Props>> {
  const response = await axios.get<Product[]>('http://localhost:3333/products');

  return {
    props: {
      products: response.data
    },
    revalidate: 10 // recriar a cada 10 segundos
  };
}

export default Home;
